#!/bin/bash
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-4-momentum.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-1-floor-kong.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-3-Over-a-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-5-split-foot.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-8-diving-cat-pass.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-CatPass/Tutorial-vaulting-cat_pass-6-standing-cat-pass.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-Precisions/Tutorial-Jumping-Precisions_3-block-to-block.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-Precisions/Tutorial-Jumping-Precisions_8-Rail-to-Rail-Precisions.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-4-over-a-rail.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-2-onto-a-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-6-chaining.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-5-over-a-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-10-side-to-rail-pre.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-3-on-and-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-8-cover-distance.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SideVault/Tutorial-vaulting-side_vault-1-up-and-on.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-DualMoves/Tutorial-flowing-Dual-moves-3-cat-180-precision.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-DualMoves/Tutorial-flowing-Dual-moves-9-lache-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-DualMoves/Tutorial-flowing-Dual-moves-1-cat-drop-to-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-DualMoves/Tutorial-flowing-Dual-moves-2-cat-to-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedVault/Tutorial-vaulting-speed_vault-6-standard-speed-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedVault/Tutorial-vaulting-speed_vault-9-scissor-kick.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedVault/Tutorial-vaulting-speed_vault-1-standing-speed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedVault/Tutorial-vaulting-speed_vault-4-two-handed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_5-Waist-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_7-180-cat-to-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_3-Upwards-Arm-Jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_1-Standing-Arm-Jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_4-Pole-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_9-crimp.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ArmJump/Tutorial-Climbing-Arm_Jump_10-height-arm-jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-2-step-turn-drop.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-6-turn-vault-precision.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-10-at-height.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-5-turn-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-7-small-drop.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-8-turn-to-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-4-side-turn-precision.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-1-step-turn.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-9-precision-turn-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TurnVault/Tutorial-vaulting-turn_vault-3-side-turn.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_3-Rail-Reposition.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_6-Leap-Frog.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_8-Danish-Flick.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_5-Perpendicular-Pistol.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_10-Jump-And-Twist.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_4-Parallel-Pistol.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_1-Step-Vault-Reposition.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-Mounting/Tutorial-Balancing-Mounting_9-Slide-Pull.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-CraneJumps/Tutorial-jumping-crane_jumps-1-crane-basics.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-3-both-feet-inside.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-2-foot-inside.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-4-pop-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-1-foot-outside.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-8-pop-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-PopVault/Tutorial-vaulting-pop_vault-5-pop-step.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-6-two-in-a-row.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-10-multiple-flow.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-3-wide-seated.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-8-two-in-a-row.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-5-over-a-rail.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-1-ground-position.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-7-slide-drop.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-4-slide-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SlideVault/Tutorial-vaulting-slide_vault-2-step-irregular.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Traversing/Tutorial-Climbing-Traversing_10-hang-traverse.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Traversing/Tutorial-Climbing-Traversing_8-Distance-Traverse-and-Climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Traversing/Tutorial-Climbing-Traversing_2-Arm-Jump-Position.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Traversing/Tutorial-Climbing-Traversing_5-lumbar-traverse.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Traversing/Tutorial-Climbing-Traversing_4-Traverse.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-RunningJumps/Tutorial-jumping-running-jumps-1-one-foot.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-RunningJumps/Tutorial-jumping-running-jumps-4-running-jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-RunningJumps/Tutorial-jumping-running-jumps-10-long-distance.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Spinning-Rotating/Tutorial-spinning-rotating-3-leg-sweep.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Spinning-Rotating/Tutorial-spinning-rotating-4-waist-360-turn.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Spinning-Rotating/Tutorial-spinning-rotating-1-cartwheel.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Spinning-Rotating/Tutorial-spinning-rotating-2-palm-spin.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Spinning-Rotating/Tutorial-spinning-rotating-5-The-Cavalier.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_5-Ground-Frog.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_6-Twists.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_8-gorilla-run.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_2-Floor-Kong.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_1-Basic-QM.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_9-duck-walk.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_7-hinge.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_4-Inverted-Table.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_3-Sideways-Monkey.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QM/Tutorial-Crawling-QM_10-Creeping-Monkey.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-1-struggle-up.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-3-high-struggle-up.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-2-low-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-6-strict-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-4-high-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-ClimbUps/Tutorial-Climbing-Climbup-5-cat-to-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-SplatCat/Tutorial-Climbing-Splat-cat-2-small-splat-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-SplatCat/Tutorial-Climbing-Splat-cat-6-higher-plyo-splat-cat.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-BoxJumps/Tutorial-jumping-box_jumps-9-box-drops.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-BoxJumps/Tutorial-jumping-box_jumps-1-box-jump-basics.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-10-walk-over.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-1-seat-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-5-reverse-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-6-kash-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-4-gate-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Obscure/Tutorial-vaulting-obscure-2-chest-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-1-crouch-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-8-drop-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-9-dive-gap-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-10-rebound-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-2-standing-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-3-jump-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-7-obstacle-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Rolling-Rolls/Tutorial-rolling-rolls-5-vault-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QMObscure/Tutorial-Crawling-QM-Obscure-9-sideways-monkey.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QMObscure/Tutorial-Crawling-QM-Obscure-1-one-handed-frogs.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QMObscure/Tutorial-Crawling-QM-Obscure-6-saddle-walk.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QMObscure/Tutorial-Crawling-QM-Obscure-2-180-sweeps.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Crawling-QMObscure/Tutorial-Crawling-QM-Obscure-5-ground-step-vaults.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Strengthening-Basics/Tutorial-strengthening-basics-8-grip-strength.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-2-step-reverse.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-7-hands-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-8-with-momentum.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-4-back-and-forward.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-3-no-momentum.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-9-on-a-rail.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-6-hop-up.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-5-reverse-stop.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-1-low-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-ReverseStep/Tutorial-vaulting-reverse_step-10-in-a-route.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Ascents/Tutorial-Climbing-Ascents_5-lumbar-vertical-climb.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Ascents/Tutorial-Climbing-Ascents_6-Pull-Over.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Ascents/Tutorial-Climbing-Ascents_2-Split-Climb.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Ascents/Tutorial-Climbing-Ascents_3-Bridging.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-DropJumps/Tutorial-jumping-drop_jumps-1-first-contact.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-DropJumps/Tutorial-jumping-drop_jumps-4-high-cat-drop.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-DropJumps/Tutorial-jumping-drop_jumps-10-drop-roll.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-DropJumps/Tutorial-jumping-drop_jumps-2-drop-jumps.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-DropJumps/Tutorial-jumping-drop_jumps-8-broad-jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-3-with-momentum.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-4-ground-level.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-1-two-handed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-6-with-speed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-7-on-a-rail.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-2-one-handed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-StepVault/Tutorial-vaulting-step_vault-9-slow-and-high.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-Lache/Tutorial-swinging-lache-2-momentum.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-Lache/Tutorial-swinging-lache-3-dismount.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-Lache/Tutorial-swinging-lache-5-regrip.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-Lache/Tutorial-swinging-lache-1-deadhang.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-Lache/Tutorial-swinging-lache-8-turning.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-Chaining/Tutorial-Chaining-6-six-vaults.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Flowing-Chaining/Tutorial-Chaining-2-Tictac-360-step-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-4-pike-underbar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-2-turning-underbar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-3-speed-underbar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-5-low-underbar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-1-basic-underbar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Passing-Underbars/Tutorial-passing-underbars-10-reverse-pike.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_6-Squats.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_7-Crouch-Walking.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_9-Sideways-Walk.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_8-Cat-Balance.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_3-Backward-Walking.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_2-Walking.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_1-one-foor-standing.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_4-Turning.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_5-Perpendicular.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Balance-RailBalance/Tutorial-Balancing-Rail_Balance_10-Height-Balance.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Koala/Tutorial-Climbing-Koala-2-climb.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Koala/Tutorial-Climbing-Koala-1-hold.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Koala/Tutorial-Climbing-Koala-6-pole-climb.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Lazy/Tutorial-vaulting-lazy-2-lazy-rail.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Lazy/Tutorial-vaulting-lazy-3-rail-run.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Lazy/Tutorial-vaulting-lazy-4-lazy-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Lazy/Tutorial-vaulting-lazy-1-lazy-around.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Lazy/Tutorial-vaulting-lazy-5-half-turn-lazy-vault.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-WallRun/Tutorial-Climbing-Wall-Run-4-wall-run-climbup.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-WallRun/Tutorial-Climbing-Wall-Run-3-wall-run.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Dyno/Tutorial-Climbing-Dynos-5-cat-to-dyno.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Climbing-Dyno/REDO-Tutorial-Climbing-Dynos_6-7-8-9-Double-Taps.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-RotatingSwing/Tutorial-swinging-rotating_swing-7-perpendicular-bar.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-6-full-dash.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-4-cat-pass-push-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-1-pushing-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-2-crouch-pushing-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-3-box-push-off.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-7-rail-dash.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-Dash/Tutorial-vaulting-dash-5-complete-dash.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-BroadJumps/Tutorial-jumping-broad_jumps-5-upwards-jump.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Jumping-BroadJumps/Tutorial-jumping-broad_jumps-7-perpendicular-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-2-over-a-wall.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-3-downwards.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-1-foot-first.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-9-alternating-down.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-6-speed-step-exit.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-7-jump-step.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-SpeedStep/Tutorial-vaulting-speed_step-4-with-speed.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TicTac/Tutorial-vaulting-tictac-5-rail-tictac.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Vaulting-TicTac/Tutorial-vaulting-tictac-9-two-steps.mp4
./run.sh /Users/andypearson/Downloads/LDNPK-Challenge-Tutorials/Outputs/Swinging-SwingTraverse/Tutorial-swinging-swing_traverse-1-hip-catch.mp4
